In [1]:
import pandas as pd
import numpy as np

## Importing Data and Cleaning it

In [2]:
dataset=pd.read_csv('churn_data.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

### Preprocessing Data

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

### Splitting the Data into Train-Test Set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


### Scaling the data

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [10]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ..., 
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Building the ANN

In [10]:
import keras
from keras.models import Sequential
from keras.layers import Dense

D:\DevTools\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


### Initializing the ANN

In [11]:
classifier=Sequential()

### Adding Input layer

In [12]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))

### Adding first hidden layer

In [13]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

### Adding output layer

In [14]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [15]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Fitting the ANN to the training set

In [16]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4872 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4274 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4221 - acc: 0.7987
Epoch 4/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4187 - acc: 0.8214
Epoch 5/100
8000/8000 [==============================] - 1s 101us/step - loss: 0.4163 - acc: 0.8270
Epoch 6/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4142 - acc: 0.8297
Epoch 7/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4131 - acc: 0.8306
Epoch 8/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4118 - acc: 0.8310
Epoch 9/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4110 - acc: 0.8327
Epoch 10/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4099 - acc: 0.8326
Epoch 1

## Making Predictions and Evaluating the Model

### Predicting the Test result

In [18]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred > 0.5)

### Making the confusion matrix

In [19]:
from sklearn.metrics import confusion_matrix
conf_matrix=confusion_matrix(y_test,y_pred)

In [20]:
conf_matrix

array([[1526,   69],
       [ 205,  200]], dtype=int64)